main: com.carlgo11.hardcore.Hardcore
name: Hardcore
version: 1.0
author: Carlgo11
website: https://github.com/Carlgo11/hardcore/
commands:

 difficulty:
   description: Get/Set game-difficulty
   usage: /<command> [set/get] (number)
   aliases: [diff]

 game:
   description: Start/stop game.
   usage: /<command> [set/get]