main: com.carlgo11.hardcore.Hardcore
name: Hardcore
version: 1.0
author: Carlgo11
website: https://github.com/Carlgo11/hardcore/
commands:

 difficulty:
   description: Get/Set game-difficulty
   usage: /<command> [set/get] (number)
   aliases: [diff]
   permission: hardcore.difficulty

 game:
   description: Start/stop game.
   usage: /<command> [set/get]
   permission: hardcore.game

 vote:
   description: Vote on things.
   usage: /<command>
   permission: hardcore.vote
   
 team:
   description: Team settings
   usage: /<command> accept/add/leave/new (name)
   permission: hardcore.team

permissions:

     hardcore.game.*:
        description: Gives access to all /game subcommands
        default: op
        children:
            hardcore.game: true
            hardcore.game.debug: true
            hardcore.game.info: true
            hardcore.game.start: true
            hardcore.game.end: true

     hardcore.vote.*:
        description: Give access to all /vote subcommands
        default: true
        children:
            hardcore.vote: true
            hardcore.vote.kick: true
            hardcore.vote.start: true
            hardcore.vote.yes: true
            hardcore.vote.no: true

     hardcore.vote.unkickable:
        description: Player becomes imune from kick votes.
        default: op

     hardcore.team.*:
        description: Give acess to all /team subcommands
        default: true
        children:
            hardcore.team.new: true
            hardcore.team.invite: true
            hardcore.team.leave: true
