name: Deploy Javadoc to GitHub Pages

on:
  push:
    branches:
      - master
    paths:
      - src/**

jobs:
  deploy:
    name: Generate & Deploy Javadoc
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v1
        name: Fetch code

      - name: Generate Javadoc
        run: |
          mvn install --settings settings.xml
          mvn javadoc:javadoc --settings settings.xml
        env:
          GITHUB_USERNAME: x-access-token
          GITHUB_TOKEN:  ${{ secrets.GITHUB_TOKEN }}

      - name: Push Javadoc to gh-pages
        working-directory: target/site/apidocs
        run: |
          remote_repo="https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
          remote_branch="gh-pages"
          git init
          git config user.name "bot"
          git config user.email "bot@users.noreply.github.com"
          git add .
          echo -n 'Files to Commit:' && ls -l | wc -l
          git commit -m'Push to GitHub Pages' > /dev/null 2>&1
          git push --force $remote_repo master:$remote_branch > /dev/null 2>&1
          rm -rf .git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ secrets.GITHUB_REPOSITORY }}
          GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}

      - uses: octokit/request-action@v1.x
        name: Deploy to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          route: POST /repos/:owner/:repo/pages/builds
